name: deploy
on:
    pull_request:
        types: [ created,opened,reopened,synchronize]
        branches: [ "dev","test","acc","main" ]
jobs:
    parameter_preparation:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: parameter_preparation
              run: |
                if [[ ${{github.base_ref}} == "dev" ]]; then
                    echo "env_path=env\\dev" >> $GITHUB_ENV
                    echo "CLIENT_ID=${{secrets.CLIENT_ID}}" >> $GITHUB_ENV
                    echo "CLIENT_SECRET=${{secrets.CLIENT_SECRET}}" >> $GITHUB_ENV
                    echo "SUBSCRIPTION_ID=${{secrets.SUBSCRIPTION_ID}}" >> $GITHUB_ENV
                    echo "TENANT_ID=${{secrets.TENANT_ID}}" >> $GITHUB_ENV

                elif [[ ${{github.base_ref}} == "test"  ]]; then
                    echo "env_path=env\\test" >> $GITHUB_ENV
                    echo "CLIENT_ID=${{secrets.CLIENT_ID}}" >> $GITHUB_ENV
                    echo "CLIENT_SECRET=${{secrets.CLIENT_SECRET}}" >> $GITHUB_ENV
                    echo "SUBSCRIPTION_ID=${{secrets.SUBSCRIPTION_ID}}" >> $GITHUB_ENV
                    echo "TENANT_ID=${{secrets.TENANT_ID}}" >> $GITHUB_ENV
                elif [[ ${{github.base_ref}} == "acc"  ]]; then
                    echo "env_path=env\\acc" >> $GITHUB_ENV
                    echo "CLIENT_ID=${{secrets.CLIENT_ID}}" >> $GITHUB_ENV
                    echo "CLIENT_SECRET=${{secrets.CLIENT_SECRET}}" >> $GITHUB_ENV
                    echo "SUBSCRIPTION_ID=${{secrets.SUBSCRIPTION_ID}}" >> $GITHUB_ENV
                    echo "TENANT_ID=${{secrets.TENANT_ID}}" >> $GITHUB_ENV

                elif [[ ${{github.base_ref}} == "main"  ]]; then
                    echo "env_path=env\\prod" >> $GITHUB_ENV
                    echo "CLIENT_ID=${{secrets.CLIENT_ID}}" >> $GITHUB_ENV
                    echo "CLIENT_SECRET=${{secrets.CLIENT_SECRET}}" >> $GITHUB_ENV
                    echo "SUBSCRIPTION_ID=${{secrets.SUBSCRIPTION_ID}}" >> $GITHUB_ENV
                    echo "TENANT_ID=${{secrets.TENANT_ID}}" >> $GITHUB_ENV
    validation:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6.0.2
            - name: HashiCorp - Setup Terraform
              # You may pin to the exact commit or the version.
              # uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
              uses: hashicorp/setup-terraform@v2.0.3
              with: 
                terraform_version: 'latest'
            - name: terraform init
              env:
                ARM_CLIENT_ID: $CLIENT_ID
                ARM_CLIENT_SECRET: $CLIENT_SECRET
                ARM_TENANT_ID: $TENANT_ID
                ARM_SUBSCRIPTION_ID: $SUBSCRIPTION_ID
              run:
                terraform init
            - name: terrform_validate
              run: |
                echo $env_path
                terraform --version
                terraform validate
                terraform fmt -recursive .

                
