name: validation
on:
    pull_request:
        types: [ created,opened,reopened,synchronize]
        branches: [ "dev","release/**","main" ]
jobs:
    parameter_preparation:
        runs-on: ubuntu-latest
        steps:
            - name: parameter_preparation
              run: |
                if [[ ${{github.base_ref}} == 'dev' ]]; then
                    echo "ENV_PATH=env/dev" >> $GITHUB_ENV
                    echo "CLIENT_ID=${{secrets.CLIENT_ID}}" >> $GITHUB_ENV
                    echo "CLIENT_SECRET=${{secrets.CLIENT_SECRET}}" >> $GITHUB_ENV
                    echo "SUBSCRIPTION_ID=${{secrets.SUBSCRIPTION_ID}}" >> $GITHUB_ENV
                    echo "TENANT_ID=${{secrets.TENANT_ID}}" >> $GITHUB_ENV

                elif [[ ${{github.base_ref}} == 'release/*'  ]]; then
                    echo "ENV_PATH_TEST=env/test" >> $GITHUB_ENV
                    echo "CLIENT_ID_TEST=${{secrets.CLIENT_ID}}" >> $GITHUB_ENV
                    echo "CLIENT_SECRET_TEST=${{secrets.CLIENT_SECRET}}" >> $GITHUB_ENV
                    echo "SUBSCRIPTION_ID_TEST=${{secrets.SUBSCRIPTION_ID}}" >> $GITHUB_ENV
                    echo "TENANT_ID_TEST=${{secrets.TENANT_ID}}" >> $GITHUB_ENV

                    echo "ENV_PATH_ACC=env/acc" >> $GITHUB_ENV
                    echo "CLIENT_ID_ACC=${{secrets.CLIENT_ID}}" >> $GITHUB_ENV
                    echo "CLIENT_SECRET_ACC=${{secrets.CLIENT_SECRET}}" >> $GITHUB_ENV
                    echo "SUBSCRIPTION_ID_ACC=${{secrets.SUBSCRIPTION_ID}}" >> $GITHUB_ENV
                    echo "TENANT_ID_ACC=${{secrets.TENANT_ID}}" >> $GITHUB_ENV

                elif [[ ${{github.base_ref}} == 'main'  ]]; then
                    echo "ENV_PATH=env/prod" >> $GITHUB_ENV
                    echo "CLIENT_ID=${{secrets.CLIENT_ID}}" >> $GITHUB_ENV
                    echo "CLIENT_SECRET=${{secrets.CLIENT_SECRET}}" >> $GITHUB_ENV
                    echo "SUBSCRIPTION_ID=${{secrets.SUBSCRIPTION_ID}}" >> $GITHUB_ENV
                    echo "TENANT_ID=${{secrets.TENANT_ID}}" >> $GITHUB_ENV
                fi
    validation:
        if: github.base_ref == 'dev' || github.base_ref == 'main'
        needs: [parameter_preparation]
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6.0.2
            - name: HashiCorp - Setup Terraform
              # You may pin to the exact commit or the version.
              # uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
              uses: hashicorp/setup-terraform@v2.0.3
              with: 
                terraform_version: 'latest'
            - name: terraform init
              env:
                ARM_CLIENT_ID: $CLIENT_ID
                ARM_CLIENT_SECRET: $CLIENT_SECRET
                ARM_TENANT_ID: $TENANT_ID
                ARM_SUBSCRIPTION_ID: $SUBSCRIPTION_ID
              run:
                terraform init
                ls -ltra $ENV_PATH
                pwd
              working-directory: ${{env.ENV_PATH}}
            - name: terrform_validate
              run: |
                terraform --version
                terraform validate
                terraform fmt -check -recursive
              working-directory: ${{env.ENV_PATH}}
            - name: Terraform Plan
              env:
                ARM_CLIENT_ID: $CLIENT_ID
                ARM_CLIENT_SECRET: $CLIENT_SECRET
                ARM_TENANT_ID: $TENANT_ID
                ARM_SUBSCRIPTION_ID: $SUBSCRIPTION_ID
              run:
                terraform plan
              working-directory: ${{env.ENV_PATH}}
                
    validation_test:
        if: startsWith(github.base_ref, 'release/')
        needs: [parameter_preparation]
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6.0.2
            - name: HashiCorp - Setup Terraform
              # You may pin to the exact commit or the version.
              # uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
              uses: hashicorp/setup-terraform@v2.0.3
              with: 
                terraform_version: 'latest'
            - name: terraform init
              env:
                ARM_CLIENT_ID: $CLIENT_ID_TEST
                ARM_CLIENT_SECRET: $CLIENT_SECRET_TEST
                ARM_TENANT_ID: $TENANT_ID_TEST
                ARM_SUBSCRIPTION_ID: $SUBSCRIPTION_ID_TEST
              run:
                terraform init
              working-directory: ${{env.ENV_PATH_TEST}}
            - name: terrform_validate
              run: |
                terraform --version
                terraform validate
                terraform fmt -check -recursive
              working-directory: ${{env.ENV_PATH_TEST}}
            - name: Terraform Plan
              env:
                ARM_CLIENT_ID: $CLIENT_ID
                ARM_CLIENT_SECRET: $CLIENT_SECRET
                ARM_TENANT_ID: $TENANT_ID
                ARM_SUBSCRIPTION_ID: $SUBSCRIPTION_ID
              run:
                terraform plan
              working-directory: ${{env.ENV_PATH_TEST}}
    validation_acc:
        needs: [validation_test,parameter_preparation]
        if: startsWith(github.base_ref, 'release/')
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6.0.2
            - name: HashiCorp - Setup Terraform
              # You may pin to the exact commit or the version.
              # uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
              uses: hashicorp/setup-terraform@v2.0.3
              with: 
                terraform_version: 'latest'
            - name: terraform init
              env:
                ARM_CLIENT_ID: $CLIENT_ID_ACC
                ARM_CLIENT_SECRET: $CLIENT_SECRET_ACC
                ARM_TENANT_ID: $TENANT_ID_ACC
                ARM_SUBSCRIPTION_ID: $SUBSCRIPTION_ID_ACC
              run:
                terraform init
              working-directory: ${{env.ENV_PATH_ACC}}
            - name: terrform_validate
              run: |
                terraform --version
                terraform validate
                terraform fmt -check -recursive
              working-directory: ${{env.ENV_PATH_ACC}}
            - name: Terraform Plan
              env:
                ARM_CLIENT_ID: $CLIENT_ID
                ARM_CLIENT_SECRET: $CLIENT_SECRET
                ARM_TENANT_ID: $TENANT_ID
                ARM_SUBSCRIPTION_ID: $SUBSCRIPTION_ID
              run:
                terraform plan
              working-directory: ${{env.ENV_PATH_ACC}}